"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r)hok=-+uo57#%^eteguc_9$+p3_r#q#fi(48@y8vp8)gft8bf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend.core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


APP_DOMAIN = 'https://1fc3-149-102-245-74.ngrok-free.app'

# Kenar Divar: https://divar.ir/kenar
DIVAR_AUTHORIZATION_HEADER_KEY = 'divarsecret'
DIVAR_API_TOKEN = 'eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGVfa2V5XzIiLCJ0eXAiOiJKV1QifQ.eyJhcHBfc2x1ZyI6IndlbGwtZG9nLW15dGgiLCJhdWQiOiJzZXJ2aWNlcHJvdmlkZXJzIiwiZXhwIjoxNzM1MDc4MjIxLCJqdGkiOiJlZDZjODhhZS05MzFkLTExZWYtYjM1ZS1mYWFiMDYxNzA5ZmMiLCJpYXQiOjE3Mjk4OTQyMjEsImlzcyI6ImRpdmFyIiwic3ViIjoiYXBpa2V5In0.OLW0kVZsFLw4bp4qDTD7NZw9EatjcVnVYZa3F-7OsXWN2iuG34-SG-O1-2W9sBJSkUpZKnG2jgfgLUa_3SNopwGO7Az1FtwVyXQ968dQu4gDclnX3i1xYzM1jja8j0bL0Ikg74sYIjMPOLKc6eGjca60BExkF6fJ2RZtMhlPrCygOXZN11v_asxhdaEN7sXlddKvZysrLTcUZBIQsG9D51M3knGUoyteduf1_vrgmUx_rIDppZmuCJl_Co2oaX3-ZCuwd-Ha3m-IN6YDHMC-ODfden03VZDu3pFAprBmpZ1mHlehNWQa4vMwOh9aLQMcJP39yuFceS-JKe-TTO_UWA'
DIVAR_OAUTH_CLIENT_SECRET = '6d861aefd0932e6fa8956ca7d565294ac0d315ac01417a3550c3cd865ae93b41613a2fcb3502ca324709c0760a2fe0bf65d4ea2c2f5bb195d48e207758f0e476'
DIVAR_OAUTH_CLIENT_ID = 'well-dog-myth'
DIVAR_OAUTH_REDIRECT_URL = APP_DOMAIN + '/auth/divar/callback'
DIVAR_ON_MESSAGE_HOOK_URL = APP_DOMAIN + '/hook/on-message'
