# Generated by Django 5.1.2 on 2024-10-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('divar_post_token', models.TextField(unique=True)),
                ('divar_post_return_url', models.TextField(unique=True)),
                ('divar_post_data', models.JSONField(default=dict)),
                ('knowledge', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.TextField()),
                ('supplier_id', models.TextField()),
                ('messages', models.TextField(default=list)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.postdetail')),
            ],
        ),
    ]
