# Generated by Django 5.1.2 on 2024-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='divar_access_token',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
